---
title: " "
output: github_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  fig.path = "README_figs/README-",
  message = FALSE,
  warning = FALSE)

library(tidyverse)
library(tidycensus)
library(sf)

options(tigris_class = "sf", tigris_use_cache = TRUE)

sf_dots <- read_csv("~/Desktop/DataProjects/Census Origins/Data/origin_dots.csv")
sf_dots2 <- read_csv("~/Desktop/DataProjects/Census Origins/Data/origin_dotsEUR.csv")
sf_dots3 <- read_csv("~/Desktop/DataProjects/Census Origins/Data/origin_dots3.csv")

states <- get_acs(geography = "state", variables = "B03001_016E", geometry = TRUE,
                  shift_geo = TRUE)


sf_dots %>% group_by(Origin) %>% summarise(count = n()) %>% arrange(count)

sf_dots$Origins <- factor(sf_dots$Origin, levels = c("Mexico", "Paraguay", "Uruguay" ,  "Bolivia", "Puerto.Rico","Costa.Rica", "Chile",
"Panama","Cuba", "Ecuador" , "El.Salvador",  "Guatemala", "Nicaragua", 
"Honduras","Dominican.Rebublic" ,"Colombia",  "Peru" , "Venezuela", "Argentina"))                  

sf_dots2 %>% group_by(Origin) %>% summarise(count = n()) %>% arrange(count)
sf_dots2$Origins <- factor(sf_dots2$Origin, levels = c("German", "Celtic", "Irish",
                                                      "Greek", "Italian","British", "Polish"))

NW <- sf_dots3 %>% filter(Race != "White") 

```

## Geographic Distribution of the US Population by select Race and Ethnicity


```{r, echo=FALSE, fig.height= 7, fig.width=9}

ggplot()  + geom_sf(data = states, fill = NA, color = "#7f7f7f") + 
  geom_point(data = sf_dots, aes(lon, lat, color = Origins), size = .5) +
  theme_minimal() +  theme(axis.text = element_blank(), legend.position = "bottom") +
  scale_color_viridis_d() + guides(colour = guide_legend(override.aes = list(size=3))) +
  ggtitle("US Hispanic/Latino Population by Country of Origin", subtitle = " 1 dot = 50 people") +
  labs(x = "", y = "",color = "", caption = "Data: US Census - 2016 5-year ACS estimates")

```




```{r, echo=FALSE, fig.height= 7, fig.width=9}

ggplot()  + geom_sf(data = states, fill = NA, color = "#7f7f7f") + 
  geom_point(data = sf_dots2, aes(lon, lat, color = Origins), size = .5) +
  theme_minimal() +  theme(axis.text = element_blank(), legend.position = "bottom") +
  scale_color_viridis_d() + guides(colour = guide_legend(override.aes = list(size=3))) +
  ggtitle("US Population by Single Ancestry", subtitle = " 1 dot = 100 people") +
  labs(x = "", y = "",color = "", caption = "Data: US Census - 2016 5-year ACS estimates")

```



```{r, echo=FALSE, fig.height= 7, fig.width=9}

ggplot()  + geom_sf(data = states, fill = NA, color = "#7f7f7f") + 
  geom_point(data = sf_dots3, aes(lon, lat, color = Race), size = .25) +
  theme_minimal() +  theme(axis.text = element_blank(), legend.position = "bottom") +
  scale_color_viridis_d() + guides(colour = guide_legend(override.aes = list(size=3))) +
  ggtitle("US Population by Race", subtitle = " 1 dot = 300 people") +
  labs(x = "", y = "", color = "", caption = "Data: US Census - 2016 5-year ACS estimates")

```



```{r, echo=FALSE, fig.height= 7, fig.width=9}

ggplot()  + geom_point(data = NW, aes(lon, lat, color = Race), size = .5) +
  geom_sf(data = states, fill = NA, color = "#7f7f7f") + 
  theme_minimal() +  theme(axis.text = element_blank(), legend.position = "bottom") +
  scale_color_viridis_d() + guides(colour = guide_legend(override.aes = list(size=3))) +
  ggtitle("US Population by Non-White Race ", subtitle = "1 dot = 300 people") +
  labs(x = "", y = "", color = "", caption = "Data: US Census - 2016 5-year ACS estimates")

```